base_model:
  name: resnet18
  weights: IMAGENET1K_V1
  num_classes: 3
  freeze_base: true
  image_size: [224, 224]
  log_model_summary: true
  learning_rate: 0.001

training:
  epochs: 23
  batch_size: 32
  learning_rate: 0.001
  optimizer: Adam
  loss_fn: CrossEntropyLoss
  device: "cpu"
  patience: 5
  val_split: 0.2
  checkpoint_interval: 5

  
